from flask import Flask, request, render_template
import re
import random
import nltk
from nltk.tokenize import sent_tokenize
from nltk import word_tokenize, ne_chunk, pos_tag
from textblob import TextBlob
import sys

reload(sys)
sys.setdefaultencoding('utf8')

global neutral_counter
neutral_counter = 0
global mood_meter
mood_meter= 0
global poem
poem = ''

app = Flask(__name__)

@app.route('/')
def home():
    global neutral_counter
    global mood_meter
    global poem
    poem = ''
    neutral_counter = 0
    mood_meter = 0
    return render_template("home.html")

@app.route('/transformed', methods=["POST"])
def transformed():
    global neutral_counter
    global mood_meter
    global poem
    text = request.form['text']
    negative_5 = ['What blurt is this about virtue and about vice? \\nEvil propels me, and reform of evil propels me - I stand indifferent.\n',
 'The sickness of one of my folks, or of myself, or ill-doing, or loss or lack of money, or depressions or exaltations; \\nBattles, the horrors of fratricidal war, the fever of doubtful news, the fitful events; \n',
 'The suicide sprawls on the bloody floor of the bed-room;\\nI witness the corpse with its dabbled hair - I note where the pistol has fallen.\n',
 'Of every hue and caste am I, of every rank and religion;\\nA farmer, mechanic, artist, gentleman, sailor, quaker, prisoner, fancy-man, rowdy, lawyer, physician, priest.\n',
 'Partaker of influx and efflux I - extoller of hate and conciliation;\\nExtoller of amies, and those that sleep in each others\xe2\x80\x99 arms.\n',
 'The riders spur their unwilling horses, haul close, \\nTaunt my dizzy ears, and beat me violently over the head with whip-stocks.\n',
 'And there are corpses, \\nFeet made of cold and sticky clay,\n',
 'Every angel is terrifying. \\nAnd yet, alas, I invoke you, almost deadly birds of the soul, knowing about you.\n',
 'Imagine surrender. \\nImagine being useless.\n',
 'Here you are in the straw house, feeding the straw dog. \\nHere you are in the wrong house, feeding the wrong dog.\n',
 'Do we simply stare at what\xe2\x80\x99s horrible and forgive it? \\nHere is the river, and here is the box, and here are the monsters we put in the box to test our strength against.\n',
 'Sometimes I think the sea is angry. \\nWho can blame it?\n',
 "You're sad because you're sad. \\nIt's psychic. \n",
 'Well, all children are sad but some get over it. \\nCount your blessings. \n',
 'Life is a giant battle. I will be your shield and spear; \\nYour spear to pierce through the horrible people who want to harm you.\n',
 'They were my slaves--the only care they had, \\nTo know what secret grief had made me sad.\n',
 'Negative space is silly. \\nWhen you bang on the wall you have to remember you\xe2\x80\x99re on both sides of it already but go ahead, yell at yourself. \n',
 "He feared, in his secret heart, that one day in company the baby would sit up and speak. \\nThat it would engage his eyes, appraise him, and say, 'You prick.\n",
 "No show of bolts and bars can keep the foeman out, or 'scape his secret mine, \\nWho entered with the doubt that drew the line. \n",
 'But I can\xe2\x80\x99t look at her, can hardly speak, I took the bullet for all the wrong reasons, \\nI\xe2\x80\x99d just as soon kill you myself, I say.\n',
 'Hello darling, sorry about that. \\nSorry about the bony elbows, sorry we lived here, sorry about the scene at the bottom of the stairwell and how I ruined everything by saying it out loud. \n',
 'I lie in the night air in my red shirt - the pervading hush is for my sake. \\nPainless after all I lie, exhausted but not so unhappy.\n',
 'Is there an acceptable result? \\nDo we mean something when we talk?\n',
 'I will go to the bank by the wood, and become undisguised and naked; \\nI am mad for it to be in contact with me.\n',
 "A stone on the path means the tea's not ready. \\nA stone in the hand means somebody's angry, the stone inside you still hasn't hit bottom.\n",
 "You have a cold cold smile. \\nYou were burned, you were about to burn, you're still on fire.\n",
 'Do not accept these rains that come too late. \\nBetter to linger. \n',
 "For it no hour's too late that witnesseth one duty's end, \\nOr to another doth beginning lend. \n",
 'It\xe2\x80\x99s a fairy tale, the story underneath the story, sliding down the polished halls, lightning here and gone.\\n We make these ridiculous idols so we can pray to what\xe2\x80\x99s behind them, but what happens after we get up the ladder?\n',
 'I arrived in the city and you met me at the station, smiling in a way that made me frightened. \\nDown the alley, around the arcade, up the stairs of the building to the little room with the broken faucets, your drawings, all your thing.\n',
 'I embody all presences outlaw\xe2\x80\x99d or suffering, \\nSee myself in prison shaped like another man and feel the dull unintermitted pain.\n',
 "Let's say God in his High Heaven is hungry and has decided to make himself some tuna fish sandwiches. \\nHe's already finished making two of them, on sourdough, before he realizes that the fish is bad.\n",
 'For beauty is nothing but the beginning of terror, which we still are just able to endure, and we are so awed because it serenely disdains to annihilate us. \\nEvery angel is terrifying.\n',
 'Begin again and again the never-attainable praising. \\nRemember: the hero lives on; even his downfall was merely a pretext for attaining his final birth.\n',
 " I take off my hands and I give them to you but you don't want them, so I take them back and put them on the wrong way, the wrong wrists. \\nThe yard is dark, the tomatoes are next to the whitewashed wall, the book on the table is about Spain, the windows are painted shut.\n",
 'Permit yourself anger and permit me mine, which needs neither your approval nor your surprise, which does not need to be made legal, which is not against a disease but against you, which does not need to be understood, or washed or cauterized, which needs instead to be said and said. \\nPermit me the present tense. \n',
 'Limitless are leaves, stiff or drooping in the fields, and brown ants in the little wells beneath them; \\nAnd mossy scabs of the worm fence, and heap\xe2\x80\x99d stones, elder, mullen and poke-weed.\n',
 'Not because I don\xe2\x80\x99t believe it, not because I want it any different, but I\xe2\x80\x99m always saving and you\xe2\x80\x99re always owing and I\xe2\x80\x99m tired of asking to settle the debt. \\nDon\xe2\x80\x99t bother.\n',
 'Consider the hairpin turn. \\nIt is waiting for you like a red door or the broken leg of a dog.\n',
 'It is waiting, like a broken door, \\nLike the red dog that chases its tail and eats your rosebushes and then must be forgiven.\n']
    negative_4 = ['I was away, I don\xe2\x80\x99t know where, lying on the floor, pretending I was dead. \\nI wanted to hurt you but the victory is that I could not stomach it.\n',
 'From the landscape: a sense of scale. \\nFrom the dead: a sense of scale.\n',
 'The face of death is green, and the look death gives is green, \\nWith the penetrating dampness of a violet leaf and the somber color of embittered winter.\n',
 'But death also goes through the world dressed as a broom, \\nLapping the floor, looking for dead bodies,\n',
 'I guess it must be the flag of my disposition, out of hopeful green stuff woven. \\nOr I guess it is the handkerchief of the Lord.\n',
 'I beat and pound for the dead; \\nI blow through my embouchures my loudest and gayest for them.\n',
 'I visit the orchards of spheres, and look at the product, \\nAnd look at quintillions ripen\xe2\x80\x99d, and look at quintillions green.\n',
 'Voices. Listen, my heart, as only saints have listened: until the gigantic call lifted them off the ground; \\nYet they kept on, impossibly, kneeling and didn\xe2\x80\x99t notice at all: so complete was their listening.\n',
 'When we were little we made houses out of cardboard boxes. \\nWe can do anything.\n',
 'They are the same and they are not the same. \\nThey are the same and they hate each other for it.\n',
 'I\xe2\x80\x99m not sure, I understand only a little, I can hardly see, but \\nIt seems to me that its singing has the color of damp violets, of violets that are at home in the earth,\n',
 'To be a man on a hill, or all the men on all the hills, or half a man shivering in the flock of himself. \\nThese are some choices.\n',
 'The early languages are obsolete. \\nThese days we keep our weary distances: sparring in the vacant spaces of peeling rooms and rented minutes, climbing all the expected stairs, our voices abraded with fatigue, our bodies wary.\n',
 'And being dead is hard work and full of retrieval before one can gradually feel a trace of eternity. \\nThough the living are wrong to believe in the too-sharp distinctions which they themselves have created.\n',
 'Somehow you escaped and climbed up the branches of a pear tree. \\nI chopped it down but there was no one in it.\n',
 'Death is inside the folding cots: \\nIt spends its life sleeping on the slow mattresses, in the black blankets, and suddenly breathes out:\n',
 'Angels (they say) don\xe2\x80\x99t know whether it is the living they are moving among, or the dead. \\nThe eternal torrent whirls all ages along in it, through both realms forever, and their voices are drowned out in its thunderous roar.\n',
 'Distant and dead resuscitate. \\nThey show as the dial or move as the hands of me - I am the clock myself.\n',
 'We are not traitors but the lights go out. \\nIt\xe2\x80\x99s dark.\n',
 "I held you through all your shifts of structure. \\nWhile your bones turned from caved rock back to marrow, the dangerous fur faded to hair, the bird's cry died in your throat, the treebark paled from your skin, the leaves from your eyes, till you limped back again to daily man.\n",
 "Now I wouldn't be bored. \\nNow I would know too much.\n",
 'They do not sweat and whine about their condition; \\nThey do not lie awake in the dark and weep for their sins.\n',
 'Hurrying with the modern crowd, as eager and fickle as any; \\nHot toward one I hate, ready in my madness to knife her.\n',
 'My respiration and inspiration, the beating of my heart, the passing of blood and air through my lungs; \\nThe sniff of green leaves and dry leaves, and of the shore, and dark-color\xe2\x80\x99d sea-rocks, and of hay in the barn.\n',
 'Every morning the maple leaves. \\nEvery morning another chapter where the hero shifts from one foot to the other.\n',
 'The eye stretches to the horizon and then must continue up. \\nAnything past the horizon is invisible, it can only be imagined. \n',
 'A thing and a thing and a thing held still  -  you have to hold something still to find the other things. \\nThis is speculation.\n',
 'Let\xe2\x80\x99s admit, without apology, what we do to each other. \\nWe know who our enemies are. \n',
 'They looked at the sky, and at the mud, and at their hands in the mud, and their dead friends in the mud. \\nThis went on for a long time.\n',
 'You hold each other. \\nWhere is your proof?\n',
 'You think you cannot keep breathing, but your ribcage has other ideas, rising and falling, emitting sighs. \\nYou must thrive in spite of yourself; and so that you may do it, God takes out your heart of flesh, and gives you a heart of stone.\n',
 'We look to each other, \\nAnd feel the warmth of a Noonday sun.\n',
 'I believe in you, my Soul - the other I am must not abase itself to you; \\nAnd you must not be abased to the other.\n',
 'Never such innocence, never before or since, \\nAs changed itself to past without a word.\n',
 ' History throws its shadow over the beginning, over the desktop, over the sock drawer with its socks, its hidden letters. \\nHistory is a little man in a brown suit trying to define a room he is outside of.\n',
 'No horizontal weeping; no weeping vertically. \\nNo flipping back your black tails at the black piano bench.\n',
 "Was there no one else? \\nLeft-handed truth, right-handed truth, there's no pure way to say it.\n",
 'The constant shuttling of opinions is tiring, and the shuffling of papers across desks, the chopping of logic and the trimming of attitudes. \\nThere must, somewhere, be a simpler, more violent world.\n',
 "It's early in the morning, and they are doing this thing together. \\nThey come on, slowly.\n",
 "I'm sorry it's such a lousy story. \\nDear Forgiveness, you know that recently we have had our difficulties and there are many things I want to ask you.\n"]
    negative_3 = ['The birds were watching you. \\nYour eyes were closed and you were listening to the road and I could hear your breathing, I could hear your heart beating.\n',
 'Here are the illuminated cities at the center of me, and here is the center of me, which is a lake, which is a well that we can drink from, but I can\xe2\x80\x99t go through with it. \\nI just don\xe2\x80\x99t want to die anymore.\n',
 "I say the phrases that keep it all going, and everybody plays along. \\nI'm the director and i'm screaming at you, I'm waving my arms in the sky, and everyone's watching, everyone's curious, everyone's holding their breath.\n",
 'You had expected something else, anything else, but the wrench never reaches you. \\nIt hangs in the air like that, spinning in the air like that.\n',
 "Don't make a noise,don't leave the room until I come back from the dead for you. \\nI will come back from the dead for you.\n",
 'Accidents never happen when the room is empty. \\nPeople like to think war means something.\n',
 'Root pity in thy heart, that when it grows, \\nThy pity may deserve to pitied be.\n',
 'Looks down, is erect, or bends an arm on an impalpable certain rest, looking with side-curved head, curious what will come next; \\nBoth in and out of the game, and watching and wondering at it.\n',
 "I looked out the window and said \\nThis doesn't look that much different from home,But then I noticed the black sky and all those lights.\n",
 "Your speedometer and your handgrips and the feel of the road below you, how it knows you, \\nThe black ribbon spread out on the greens between these lines that suddenly don't reach to the horizon.\n",
 'You know what it\xe2\x80\x99s like to be alive, so forgiveness. \\nAll night the trees stand silent in the dark, not touching.\n',
 'You shall no longer take things at second or third hand, \\nNor look through the eyes of the dead, nor feed on the spectres in books; \n',
 'I think I could turn and live with animals, they are so placid and self-contained. \\nI stand and look at them long and long.\n',
 'Every morning the same big and little words all spelling out desire, all spelling out \\nYou will be alone always and then you will die. \n',
 'If I should die, and you should live, and time should gurgle on, \\nAnd morn should beam, and noon should burn, as it has usual done.\n',
 'Delicate are you, and your vows are delicate, too. \\nSo easily do they break.  \n',
 'A man takes his sadness down to the river and throws it in the river but then he\xe2\x80\x99s still left with the river. \\nA man takes his sadness and throws it away but then he\xe2\x80\x99s still left with his hands.\n',
 'Strange to no longer desire one\xe2\x80\x99s desires. \\nStrange to see meanings that clung together once, floating away in every direction.\n',
 'I kept my mind on the moon. \\nCold moon, long nights moon.\n',
 'If ever there was death, it led forward life, and does not wait at the end to arrest it, \\nAnd ceas\xe2\x80\x99d the moment life appear\xe2\x80\x99d.\n',
 "It's thinking of love. \\nIt's thinking of stabbing us to death and leaving our bodies in a dumpster.\n",
 "It seems a bit late to be having this conversation. \\nI've had to take up violence now, and so much else.\n",
 'Sometimes I see alone coffins under sail, embarking with the pale dead, with women that have dead hair, \\nWith bakers who are as white as angels, and pensive young girls married to notary publics,\n',
 'The sentries desert every other part of me. \\nThey have left me helpless to a red marauder.\n',
 "I never liked that ending either. \\nMore love streaming out the wrong way, and I don't want to be the kind that says the wrong way.\n",
 'I will not have a single person slighted or left away; \\nThe kept-woman, sponger, thief, are hereby invited. \n',
 'Sunlight pouring across your skin, your shadow flat on the wall. \\nThe dawn was breaking the bones of your heart like twigs.\n',
 "So early it's still almost dark out. \\nI'm near the window with coffee, and the usual early morning stuff that passes for thought.\n",
 "They dismantled us each from the other. \\nAs far as I'm concerned they are all engineers. \n",
 'I am there - I help - I came stretch\xe2\x80\x99d atop of the load; \\nI felt its soft jolts - one leg reclined on the other.\n',
 'I do not love you except because I love you; \\nI go from loving to not loving you, from waiting to not waiting for you my heart moves from cold to fire.\n',
 "Let such pure hate still underprop Our love, \\nThat we may be each other's conscience, and have our sympathy mainly from thence. \n",
 'We know how it works. \\nThe world is no longer mysterious.\n',
 'History repeats itself. \\nSomebody says this.\n',
 'The seaside town. \\nThe electric fence.\n',
 "There's a thing in my stomach about this. \\nA simple thing.\n",
 "But the minutes don't stop. \\nThe prayer of going nowhere, going nowhere.\n",
 "I'm not the dragon. \\nI'm not the princess either.\n",
 'For a while I thought I was the dragon. \\nI guess I can tell you that now.\n',
 'There is something underneath the floorboards. \\nCrossed out.\n']
    negative_2 = ['Dear Forgiveness, I saved a plate for you. \\nQuit milling around the yard and come inside.\n',
 'The wind blows and it makes a noise. \\nPain makes a noise.\n',
 'His hands keep turning into birds, and his hands keep flying away from him. \\nEventually the birds must land.\n',
 "I went to the riverbed to wait for you to show up. \\nYou didn't show up.\n",
 'You saved my life, she says. \\nI owe you everything.\n',
 'You keep saying I owe you, I owe... but you say the same thing every time. \\nLet\xe2\x80\x99s not talk about it, let\xe2\x80\x99s just not talk.\n',
 'I\xe2\x80\x99m battling monsters, I\xe2\x80\x99m pulling you out of the burning buildings and you say I\xe2\x80\x99ll give you anything. \\nBut you never come through.\n',
 'This is not harmless. \\nYou are not breathing.\n',
 'We have not been given all the words necessary. \\nWe have not been given anything at all.\n',
 "We want to stop. \\nWe can't.\n",
 "They want to stop but they can't stop. \\nThey don't know what they're doing.\n",
 "They've been going at it for days now. \\nGetting the bullet out.\n",
 'Do not choose sides yet. \\nIt is still to your advantage to remain impartial.\n',
 'Hold onto your voice. \\nHold onto your breath.\n',
 'I make up things that I would never say. \\nI say them very quietly.\n',
 'All your friends are gone. \\nGoodbye.\n',
 'I would like to meet you all in Heaven. \\nBut there\xe2\x80\x99s a litany of dreams that happens somewhere in the middle.\n',
 'We have been very brave, we have wanted to know the worst, wanted the curtain to be lifted from our eyes. \\nThis dream going on with all of us in it.\n',
 'I made this place for you. \\nIf this isn\xe2\x80\x99t a kingdom then I don\xe2\x80\x99t know what is.\n',
 'I was trying to describe the kingdom, but the letters kept smudging as I wrote them: the hunter\xe2\x80\x99s heart, the hunter\xe2\x80\x99s mouth, the trees and the trees and the space between the trees, swimming in gold. \\nThe words frozen.\n',
 'We are all going forward. \\nNone of us are going back.\n',
 'See: she arose and slept. \\nWhere is her death now?\n',
 'Ah, will you discover this theme before your song consumes itself? \\nWhere is she vanishing?\n',
 'Our mind is split. \\nAnd at the shadowed crossing of heart-roads, there is no temple for Apollo.\n',
 'You will die in your sleep and leave everything unfinished. \\nThis is also speculation.\n',
 'I had obligations: hope, but hope negates the experience. \\nI owe myself nothing.\n',
 'This is philosophy. \\nThese are suppositions.\n',
 'All these things and what to do with them. \\nWe carve up the world all the time.\n',
 'What can you learn from your opponent? \\nMore than you think.\n',
 'Who will master this love? \\nLove might be the wrong word.\n',
 'What else was in the woods? \\nA heart, closing.\n',
 'I turned my back on the story. \\nA sense of superiority.\n',
 'Why do anything at all? \\nNot how, because hows are easy - series or sequence, one foot after the other - but existentially why bother, what does it solve?\n',
 'Who gets to measure the distance between experience and its representation? \\nWho controls the lines of inquiry? \n',
 'There is nothing else. \\nIt reminds me of some tale, stay with me to remember, it reminds me of where I was going without you.\n',
 'Clench is a hand word. \\nHer hand is clenched. \n',
 'She couldn\xe2\x80\x99t do it. \\nThere is no way to get to the future from here.\n',
 'You asked me once, What are we made of? \\nWell, these are the things we\xe2\x80\x99re made of. \n',
 'Who does this? \\nNo one.\n',
 "You won't believe me when I tell you it is not personal. \\nIt isn't.\n"]
    negative_1 = ['She was trying to memorize the clouds before she died. \\nI confess to being jealous of the sky.\n',
 'We shall remember the things we held in our hands that slipped out. \\nWhat I have in my possession and what I do not have in my possession.\n',
 "Make your pain an image of the desert. \\nSay it's said and do not look to the west.\n",
 'The memory is no friend. \\nIt can only tell you what you no longer have: a left hand you can use, two feet that walk.\n',
 'Then what about me, what about the I confronting you on that border you are always trying to cross? \\nI am the horizon you ride towards, the thing you can never lasso.\n',
 'It\xe2\x80\x99s always the moment just before gunshot. \\nYou try & try to rise but you cannot. \n',
 'O again and again in wonder and pain, a breath, a finger grip on a cliffside. \\nYou can hold on or let go.\n',
 'Things tremble. \\nHere, where I am surrounded by an enormous landscape, which the winds move across as they come from the seas.\n',
 'You must realize that something is happening to you, that life has not forgotten you, that it holds you in its hand and will not let you fall. \\nWhy do you want to shut out of your life any uneasiness, any misery, any depression, since after all you don\xe2\x80\x99t know what work these conditions are doing inside you?\n',
 'It seems to me that almost all our sadnesses are moments of tension, which we feel as paralysis because we no longer hear our astonished emotions living. \\nBecause we are alone with the unfamiliar presence that has entered us\n',
 'Everything we trust and are used to is for a moment taken away from us; \\nBecause we stand in the midst of a transition where we cannot remain standing.\n',
 'My father doesn\xe2\x80\x99t have views. \\nHe would like to, but he can\xe2\x80\x99t take the risk.\n',
 'Jesus, what a way to end up. \\nWhen you see him, tell him I\xe2\x80\x99d be obliged if he forgets he knows me.\n',
 'They made the war. \\nThey deserve a dozen deaths, each of them.\n',
 'An example has been made. \\nA soldier slides from his saddle and vomits.\n',
 'I was always desired. \\nBut now I am valued.\n',
 'Some say the world will end in fire, \\nSome say in ice.\n',
 'From what I\xe2\x80\x99ve tasted of desire, \\nI hold with those who favor fire.\n',
 'But if it had to perish twice, \\nI think I know enough of hate to say that for destruction ice is also great and would suffice.\n',
 'If thou dost seek to have what thou dost hide, \\nBy self-example mayst thou be denied!\n',
 "We'll one another treat like gods, and all the faith we have in virtue and in truth, \\nBestow on either, and suspicion leave to gods below. \n",
 'What need confound the sphere? \\nLove can afford to wait; \n',
 'It will subserve no use, \\nMore than the tints of flowers; \n',
 'Only the independent guest \\nFrequents its bowers, inherits its bequest. \n',
 'By night consoles, \\nBy day congratulates. \n',
 'What saith the tongue to tongue? \\nWhat hearest ear of ear? \n',
 'By the decrees of fate \\nFrom year to year, does it communicate. \n',
 'For every depth it goes below, and every height above. \\nIt waits, as waits the sky, until the clouds go by.\n',
 'It shines serenely on with an eternal day, \\nAlike when they are gone, and when they stay. \n',
 'But he goes unappeased \\nWho is on kindness bent.\n',
 'The heart moving through a tunnel, \\nIn it darkness, darkness, darkness,\n',
 'Like a shipwreck we die going into ourselves, as though we were drowning inside our hearts, \\nAs though we lived falling out of the skin into the soul.\n',
 'Death is inside the bones, like a barking where there are no dogs, coming out from bells somewhere, \\nFrom graves somewhere, growing in the damp air like tears of rain.\n',
 'Death is inside the broom, the broom is the tongue of death looking for corpses, \\nIt is the needle of death looking for thread.\n',
 'Suffering cries out to us in sleepless nights, \\nIn the morning, fatigued and wrenched, begging for a reprieve from the day.\n',
 'And in that moments waiting, \\nWe think to our children, and we look to their faces, smiling faces though still starving in tattered rags.\n',
 'For someone made the Sun I tell you, \\nFor someone made the Sun.\n',
 "She's taking her time making up the reasons, \\nTo justify all the hurt inside.\n",
 "She can't remember a time when she felt needed. \\nIf love was red then she was colour blind.\n",
 "All her friends they've been tried for treason, \\nAnd crimes that were never defined.\n"]
    zero = ["Send a signal that she's hanging \\nAll her hopes on the stars.\n",
 'I conceived you in my mind. \\nI carried you around in the depth of my heart, sitting under the tree of life.\n',
 'When I see the boy and his friend walking up the road to deliver the newspaper. \\nThey wear caps and sweaters, and one boy has a bag over his shoulder.\n',
 'I loafe and invite my Soul; \\nI lean and loafe at my ease, observing a spear of summer grass.\n',
 'The play of shine and shade on the trees as the supple boughs wag; \\nThe delight alone, or in the rush of the streets, or along the fields and hill-sides; The feeling of health, the full-noon trill, the song of me rising from bed and meeting the sun.\n',
 'You shall not look through my eyes either, nor take things from me: \\nYou shall listen to all sides, and filter them from yourself.\n',
 'I have heard what the talkers were talking, the talk of the beginning and the End; \\nBut I do not talk of the beginning or the end.\n',
 'Stout as a horse, affectionate, haughty, electrical; \\nI and this mystery, here we stand.\n',
 'These come to me days and nights, and go from me again, \\nBut they are not the Me myself.\n',
 'Apart from the pulling and hauling stands what I am; \\nStands amused, complacent, compassionating, idle, unitary.\n',
 'A scented gift and remembrancer, designedly dropt, \\nBearing the owner\xe2\x80\x99s name someway in the corners, that we may see and remark, and say, Whose? \n',
 'I wish I could translate the hints about the dead young men and women, \\nAnd the hints about old men and mothers, and the offspring taken soon out of their laps.\n',
 'They are alive and well somewhere; \\nThe smallest sprout shows there is really no death.\n',
 'All goes onward and outward - nothing collapses; \\nAnd to die is different from what any one supposed, and luckier.\n',
 'I pass death with the dying, and birth with the new-wash\xe2\x80\x99d babe,\\nAnd am not contain\xe2\x80\x99d between my hat and boots. \n',
 'I am not an earth, nor an adjunct of an earth; \\nI am the mate and companion of people, all just as immortal and fathomless as myself.\n',
 'The Yankee clipper is under her sky-sails - she cuts the sparkle and scud; \\nMy eyes settle the land - I bend at her prow, or shout joyously from the deck.\n',
 'In me the caresser of life wherever moving - backward as well as forward slueing; \\nTo niches aside and junior bending.\n',
 'I believe in those wing\xe2\x80\x99d purposes, \\nAnd acknowledge red, yellow, white, playing within me.\n',
 'What is commonest, cheapest, nearest, easiest, is Me; \\nMe going in for my chances, spending for vast returns; \n',
 'I am a learner with the simplest, a teacher of the thoughtfullest; \\nA novice beginning, yet experient of myriads of seasons.\n',
 'The suns I see, and the suns I cannot see, are in their place; \\nThe palpable is in its place, and the impalpable is in its place.\n',
 'The heavy-lipp\xe2\x80\x99d slave is invited - the venerealee is invited. \\nThere shall be no difference between them and the rest.\n',
 'This is the press of a bashful hand - this is the float and odor of hair; \\nThis is the touch of my lips to yours - this is the murmur of yearning; \n',
 'Do you guess I have some intricate purpose? \\nWell, I have - for the Fourth-month showers have, and the mica on the side of a rock has.\n',
 'Do you take it I would astonish? \\nDoes the daylight astonish? \n',
 'This hour I tell things in confidence. \\nI might not tell everybody, but I will tell you.\n',
 'Months are vacuums, and the ground but wallow and filth. \\nLife is a suck and a sell, and nothing remains at the end but threadbare crape, and tears.\n',
 'Why should I pray? \\nWhy should I venerate and be ceremonious? \n',
 'I am he that walks with the tender and growing night; \\nI call to the earth and sea, half-held by the night.\n',
 'Whoever degrades another degrades me; \\nAnd whatever is done or said returns at last to me.\n',
 'Voices of the diseas\xe2\x80\x99d and despairing, and of thieves and dwarfs; \\nVoices of cycles of preparation and accretion.\n',
 'I believe in the flesh and the appetites; \\nSeeing, hearing, feeling, are miracles, and each part and tag of me is a miracle.\n',
 'Sun so generous, it shall be you! \\nVapors lighting and shading my face, it shall be you!\n',
 'I cannot tell how my ankles bend, nor whence the cause of my faintest wish; \\nNor the cause of the friendship I emit, nor the cause of the friendship I take again.\n',
 'Speech is the twin of my vision - it is unequal to measure itself. \\nIt provokes me forever.\n',
 'I help myself to material and immaterial. \\nNo guard can shut me off, nor law prevent me.\n',
 'All this I swallow - it tastes good - I like it well - it becomes mine. \\nI am the man - I suffer\xe2\x80\x99d - I was there.\n',
 'I am the hounded slave, I wince at the bite of the dogs. \\nHell and despair are upon me, crack and again crack the marksmen.\n',
 'I clutch the rails of the fence, my gore dribs, thinn\xe2\x80\x99d with the ooze of my skin, \\nI fall on the weeds and stones.\n']
    positive_1=['Agonies are one of my changes of garments. \\nI do not ask the wounded person how he feels - I myself become the wounded person.\n',
 'For me the keepers of convicts shoulder their carbines and keep watch. \\nIt is I let out.\n',
 'Then my heart with pleasure fills, \\nAnd dances with the daffodils.\n',
 'What is our life? A play of passion, \\nOur mirth the music of division.\n',
 'If you can dream - and not make dreams your master, \\nIf you can think - and not make thoughts your aim...\n',
 'If you can meet with Triumph and Disaster, \\nAnd treat those two impostors just the same...\n',
 'If you can bear to hear the truth you\xe2\x80\x99ve spoken, \\nTwisted by knaves to make a trap for fools...\n',
 'These are the thoughts of all men in all ages and lands - they are not original with me; \\nIf they are not yours as much as mine, they are nothing, or next to nothing. \n',
 'Maybe January light will consume my heart with its cruel ray, \\nStealing my key to true calm.\n',
 " You're only young once, they say, but doesn't it go on for a long time? \\nMore years than you can bear.\n",
 'My right and left arms round the sides of two friends, and I in the middle. \\nComing home with the silent and dark-cheek\xe2\x80\x99d bush-boy.\n',
 'Occasionally he would raise his right arm, then let it fall limply by his side; \\nThis was his only gesture, a staid, mechanical one. \n',
 'You are a laconic marksman. \\nYou leave me not dead but perpetually dying.\n',
 "Then there's the two of us. \\nThis word is far too short for us, it has only four letters, too sparse to fill those deep bare vacuums between the stars that press on us with their deafness.\n",
 "I wandered lonely as a cloud, \\nThat floats on high o'er vales and hills.\n",
 'Refuse to surrender. \\nTry this year too to live alone in the long summer, eat your drying bread, refrain from tears. \n',
 'Or if it do, not from those lips of thine that have profaned their scarlet ornaments, \\nAnd sealed false bonds of love as oft as mine,\n',
 'Names of spells and names of hexes, names cursed quietly under the breath, or called out loudly to fill the yard, \\nCalling you inside again, calling you home.\n',
 'Here I feel that there is no one anywhere who can answer for you those questions and feelings which, in their depths, have a life of their own; \\nFor even the most articulate people are unable to help, since what words point to is so very delicate, is almost unsayable.\n',
 'Last night, there was hail, thunder, a tornado touching down in the desert - though I was away and was not a first hand witness. \\nI was in another place, listening to the waves of the ocean crash against the shore. \n',
 'But I have thought of you often during this holiday and imagined how silent you must be in your solitary fort amongst the empty hills, \\nUpon which those large southern winds fling themselves as if they wanted to devour them in large pieces. \n',
 'We have not touched the stars, nor are we forgiven, which brings us back to the hero\xe2\x80\x99s shoulders and the gentleness that comes, not from the absence of violence, but despite the abundance of it. \\nThe lawn drowned, the sky on fire, the gold light falling backward through the glass of every room.\n',
 'Ah, whom can we ever turn to in our need? \\nNot angels, not humans, and already the knowing animals are aware that we are not really at home in our interpreted world.\n',
 'There is so much silence between the words, you say. \\nYou say, The sensed absence of God and the sensed presence amount to much the same thing, only in reverse.\n',
 "Trees outside the window and a big band sound that makes you feel like everything's okay, a feeling that lasts for one song maybe, the parentheses all clicking shut behind you. \\nThe way we move through time and space, or only time.\n",
 'In all people I see myself - none more, and not one a barleycorn less; \\nAnd the good or bad I say of myself, I say of them.\n',
 "Forget the dragon, leave the gun on the table, this has nothing to do with happiness. \\nLet's jump ahead to the moment of epiphany, in gold light, as the camera pans to where the action is, lakeside and backlit, and it all falls into frame, close enough to see the blue rings of my eyes as I say something ugly.\n",
 "I love you only because it's you the one I love; I hate you deeply, and hating you \\nBend to you, and the measure of my changing love for you is that I do not see you but love you blindly.\n",
 "Someone once told me that explaining is an admission of failure. \\nI'm sure you remember, I was on the phone with you.\n",
 'Love is my sin, and thy dear virtue hate, \\nHate of my sin, grounded on sinful loving.\n',
 'I followed myself for a long while, deep into the field. \\nTwo heads full of garbage.\n',
 "I want to tell you this story without having to be in it. \\nI'm surprised that I say it with feeling.\n",
 'Chemical names, bird names, names of fire and flight and snow, baby names, paint names, delicate names like bones in the body, \\nRumplestiltskin names that are always changing, names that no one\xe2\x80\x99s ever able to figure out. \n',
 'What is alive and what isn\xe2\x80\x99t and what should we do about it? \\nTheories: about the nature of the thing. \n',
 "They amputated your thighs off my hips. \\nAs far as I'm concerned they are all surgeons. \n",
 'If birds should build as early, \\nAnd bees as bustling go\n',
 'I mind how once we lay, such a transparent summer morning; \\nHow you settled your head athwart my hips, and gently turn\xe2\x80\x99d over upon me,\n',
 'Tenderly will I use you, curling grass; \\nIt may be you transpire from the breasts of young men.\n',
 'My final merit I refuse you - I refuse putting from me what I really am; \\nEncompass worlds, but never try to encompass me; \n',
 'The sound of the belch\xe2\x80\x99d words of my voice, words loos\xe2\x80\x99d to the eddies of the wind; \\nA few light kisses, a few embraces, a reaching around of arms.\n']
    positive_2 = ['But if the archangel now, perilous, from behind the stars took even one step down toward us: our own heart, beating higher and higher, would beat us to death. \\nWho are you?\n',
 'And these one and all tend inward to me, and I tend outward to them; \\nAnd such as it is to be of these, more or less, I am.\n',
 'You never mean it anyway, not really, and it only makes me that much more ashamed. \\nThere\xe2\x80\x99s only one thing I want, don\xe2\x80\x99t make me say it, just get me bandages, I\xe2\x80\x99m bleeding, I\xe2\x80\x99m not just making conversation.\n',
 'Shall I postpone my acceptation and realization, and scream at my eyes, \\nThat they turn from gazing after and down the road, and forthwith cipher and show me a cent, exactly the contents of one, and exactly the contents of two, and which is ahead? \n',
 'And I know I am solid and sound; \\nTo me the converging objects of the universe perpetually flow.\n',
 'Trippers and askers surround me; \\nPeople I meet - the effect upon me of my early life, or the ward and city I live in, or the nation.\n',
 'The main thing is, the constraints have come off style. \\nWhat we are saying now is that the Revolution does not proceed in a pitiless, forward direction, its politics and its language becoming ever more gross and simplistic.\n',
 'Especially that, but I should have known. \\nYou see, I take the parts that I remember and stitch them back together to make a creature that will do what I say or love me back.\n',
 'I accept reality, and dare not question it; \\nMaterialism first and last imbuing.\n',
 'The pleasures of heaven are with me, and the pains of hell are with me; \\nThe first I graft and increase upon myself - the latter I translate into a new tongue.\n',
 'Do you know me? \\nIs this microphone live?\n',
 'And all things hushed. \\nYet even in that silence a new beginning, beckoning, change appeared.\n',
 'I am enamoured of growing out-doors, of men that live among cattle, or taste of the ocean or woods, \\nOf the builders and steerers of ships, and the wielders of axes and mauls, and the drivers of horses.\n',
 'Is this then a touch? quivering me to a new identity, \\nFlames and ether making a rush for my veins.\n',
 'I exist as I am - that is enough; \\nIf no other in the world be aware, I sit content; And if each and all be aware, I sit content.\n',
 'To behold the day-break! \\nThe little light fades the immense and diaphanous shadows; The air tastes good to my palate.\n',
 "There's a part in the movie where you can see right through the acting, where you can tell that I'm about to burst into tears, \\nRight before I burst into tears and flee to the slimy moonlit riverbed canopied with devastated clouds.\n",
 '\xef\xbb\xbfTell me about the dream where we pull the bodies out of the lake and dress them in warm clothes again. \\nHow it was late, and no one could sleep, the horses running until they forget that they are horses.\n',
 'She would look out the window and stare at the trees that once had too many branches and now seemed to have too few. \\nIs that all?\n',
 'Here is a map with a your name for a capital, here is an arrow to prove a point: \\nwe laugh and it pits the world against us, We laugh, and we\xe2\x80\x99ve got nothing left to lose, and our hearts turn red, and the river rises like a barn on fire.\n',
 'Creatures of stillness crowded from the bright unbound forest, out of their lairs and nests; \\nAnd it was not from any dullness, not from fear, that they were so quiet in themselves, but from just listening. Bellow roar, shriek seemed small inside their hearts.\n',
 "So much for the facts. \\nLet's say you're still completely in the dark but we love you anyway.\n",
 'I merely stir, press, feel with my fingers, and am happy. \\nTo touch my person to someone else\xe2\x80\x99s is about as much as I can stand.\n',
 'Less the reminders of properties told, my words; \\nAnd more the reminders, they, of life untold, and of freedom and extrication.\n',
 'Life is a many things. \\nSometimes life is a dark tunnel.\n',
 'And it was almost a girl and came to be out of this single joy of song and lyre and through her green veils shone forth radiantly and made herself a bed inside my ear. \\nAnd slept there.\n',
 " I can't blame you for that, and maybe a mouth sounds idiotic when it blathers on about joy but tell me you love this, tell me you're not miserable. \\nYou do the math, you expect the trouble. \n",
 'So maybe I wanted to give you something more than a catalog of non-definitive acts, \\nSomething other than the desperation.\n',
 'It is also good to love: because love is difficult. \\nFor one human being to love another human being: that is perhaps the most difficult task that has been entrusted to us.\n',
 'One world is aware, and by far the largest to me, and that is myself; \\nAnd whether I come to my own to-day, or in ten thousand or ten million years, I can cheerfully take it now, or with equal cheerfulness I can wait.\n',
 "The entire history of human desire takes about seventy minutes to tell. \\nUnfortunately, we don't have that kind of time.\n",
 'Draw a circle with a piece of chalk. \\nImagine standing in a constant cone of light. \n',
 "I talk to you as if you're really there. \\nAre you there, princess?\n",
 'She wants to be tender and merciful. \\nThat sounds overly valorous.\n',
 'What did you really want? \\nSomeone to pass this with me.\n',
 'Is that too much to expect? \\nThat I would name the stars for you?\n',
 'But when can we be real? \\nWhen does he pour the earth, the stars, into us?\n',
 'Everyone understands this. \\nEveryone wants a battlefield.\n',
 'Why do you want to persecute yourself with the question of where all this is coming from and where it is going? \\nSince you know, after all, that you are in the midst of transitions and you wished for nothing so much as to change.\n',
 'Suffering, so much suffering astounds, \\nSuffering brings us to our very knees,\n']
    positive_3 = ['Have you reckon\xe2\x80\x99d a thousand acres much? \\nHave you reckon\xe2\x80\x99d the earth much? \n',
 'Two solitary stars-- unmeasured systems far between us roll; \\nBut by our conscious light we are determined to one pole. \n',
 'That is why young people, who are beginners in everything, are not yet capable of love: it is something they must learn. \\nWith their whole being, with all their forces, gathered around their solitary, anxious, upward-beating heart, they must learn to love.\n',
 'Caskets sailing up the vertical river of the dead, the river of dark purple, \\nMoving upstream with sails filled out by the sound of death, filled by the sound of death which is silence.\n',
 'There are cemeteries that are lonely, \\nGraves full of bones that do not make a sound,\n',
 'Clear and sweet is my Soul, and clear and sweet is all that is not my Soul. \\nLack one lacks both, and the unseen is proved by the seen, Till that becomes unseen, and receives proof in its turn.\n',
 'Dig into yourself for a deep answer. \\nAnd if this answer rings out in assent, if you meet this solemn question with a strong, simple \xe2\x80\x9cI must,\xe2\x80\x9d then build your life in accordance with this necessity; Your whole life, even into its humblest and most indifferent hour, must become a sign and witness to this impulse.\n',
 "The sky is taking on light, though the moon still hangs pale over the water. \\nSuch beauty that for a minute death and ambition, even love, doesn't enter into this.\n",
 " Love always wakes the dragon and suddenly flames everywhere. \\nI can tell already you think I'm the dragon, that would be so like me, but I'm not.\n",
 'Sure, I sink the boat of love, but that comes later. \\nAnd yes, I swallow glass, but that comes later.\n',
 'You had not expected this, the bedroom gone white, the astronomical light pummeling you in a stream of fists. \\nThe light is no mystery, the mystery is that there is something to keep the light from passing through.\n',
 'Who, if I cried out, would hear me among the angels\xe2\x80\x99 Hierarchies? \\nAnd even if one of them pressed me suddenly against his heart: I would be consumed in that overwhelming existence.\n',
 'The hand is a voice that can sing what the voice will not, and the hand wants to do something useful. \\nSometimes, at night, in bed, before I fall asleep, I think about a poem I might write, someday, about my heart, says the heart.\n',
 "Try to remember some details. \\nRemember the clothing of the one you love so that on the day of loss you'll be able to say: last seen wearing such-and-such, brown jacket, white hat. \n",
 'Address yourself to the militant, and you find a pacifist giving you a reproachful look. \\nAddress yourself to the idealist, and you\xe2\x80\x99ll find that you\xe2\x80\x99ve fallen into the company of a cheerful, breezy professional politician. \n',
 "Robbed others' beds' revenues of their rents. \\nBe it lawful I love thee as thou lov'st those whom thine eyes woo as mine importune thee.\n",
 "Love is like a barren place, \\nAnd reaching out for human faith is like a journey I just don't have a map for.\n",
 'Showing the best, and dividing it from the worst, age vexes age; \\nKnowing the perfect fitness and equanimity of things, while they discuss I am silent, and go bathe and admire myself.\n',
 'I behold the picturesque giant, and love him - and I do not stop there; \\nI go with the team also.\n',
 'And the jay in the woods never studied the gamut, yet trills pretty well to me; \\nAnd the look of the bay mare shames silliness out of me.\n',
 'I hear the sound I love, the sound of the human voice. \\nI hear all sounds running together, combined, fused or following.\n',
 'Cut me open and the light streams out. \\nStitch me up and the light keeps streaming out between the stitches.\n',
 "And, for a while, I thought I was the princess, cotton candy pink, sitting there in my room, in the tower of the castle, young and beautiful and in love and waiting for you with confidence \\nBut the princess looks into her mirror and only sees the princess, while I'm out here, slogging through the mud, breathing fire, and getting stabbed to death.\n",
 'I am of old and young, of the foolish as much as the wise; \\nRegardless of others, ever regardful of others, maternal as well as paternal, a child as well as a man.\n',
 'Stuff\xe2\x80\x99d with the stuff that is coarse, and stuff\xe2\x80\x99d with the stuff that is fine; \\nOne of the Great Nation, the nation of many nations, the smallest the same, and the largest the same.\n',
 'The latest dates, discoveries, inventions, societies, authors old and new, \\nMy dinner, dress, associates, looks, compliments, dues, the real or fancied indifference of some man or woman I love.\n',
 'Adorning myself to bestow myself on the first that will take me; \\nNot asking the sky to come down to my good will, scattering it freely forever.\n',
 "What would you like? \\nI'd like my money's worth.\n",
 'You see: I have copied out your sonnet, because I found that it is lovely and simple born in the shape that it moves in with such quiet decorum. \\nIt is the best poem of yours that you have let me read.\n',
 'I am satisfied - I see, dance, laugh, sing: \\nAs the hugging and loving Bed-fellow sleeps at my side through the night, and withdraws at the peep of the day, with stealthy tread, Leaving me baskets cover\xe2\x80\x99d with white towels, swelling the house with their plenty.\n',
 'Does the early redstart, twittering through the woods? \\nDo I astonish more than they? \n',
 'If you can fill the unforgiving minute with sixty seconds\xe2\x80\x99 worth of distance run, \\nIf you can talk with crowds and keep your virtue...\n',
 'But our love it was stronger by far than the love \\nOf those who were older than we -  Of many far wiser than we.\n',
 "There's a niche in her chest where a heart would fit perfectly and she thinks if she could just maneuver one into place. \\nWell then, game over.\n",
 'Shouldn\xe2\x80\x99t this most ancient of sufferings finally grow more fruitful for us? \\nFor there is no place where we can remain.\n',
 'Has any one supposed it lucky to be born? \\nI hasten to inform him or her, it is just as lucky to die, and I know it.\n',
 "They are so happy they aren't saying anything, these boys. \\nI think if they could, they would take each other's arm.\n",
 'Death would be fine, if I only died once. \\nI would have liked a solitary death, not this lavish funeral, this grave anyone can visit.   \n',
 'Welcome is every organ and attribute of me, and of any man hearty and clean; \\nNot an inch, nor a particle of an inch, is vile, and none shall be less familiar than the rest.\n',
 'One might depart at option from enterprise below! \\n\xe2\x80\x98Tis sweet to know that stocks will stand when we with daisies lie.\n']
    positive_4 =['Houses and rooms are full of perfumes - the shelves are crowded with perfumes; \\nI breathe the fragrance myself, and know it and like it; The distillation would intoxicate me also, but I shall not let it.\n',
 'Alone, far in the wilds and mountains, I hunt, \\nWandering, amazed at my own lightness and glee.\n',
 'That I walk up my stoop! I pause to consider if it really be. \\nA morning-glory at my window satisfies me more than the metaphysics of books.\n',
 "You're going to die in your best friend's arms. \\nAnd you play along because it's funny, because it's written down, you've memorized it, it's all you know.\n",
 'These are the dreams we should be having. \\nI shouldn\xe2\x80\x99t have to clean them up like this.\n',
 'somewhere i have never travelled, gladly beyond any experience,your eyes have their silence. \\nin your most frail gesture are things which enclose me, or which i cannot touch because they are too near.\n',
 'And those who are beautiful, oh who can retain them? \\nAppearance ceaselessly rises in their face, and is gone.\n',
 'Do you recognize anything, I said. \\nAnything familiar?\n',
 "This kind of hunger draws everything into its own space; nor can we talk it all over, have a calm rational discussion. \\nThere is no reason for this, only a starved dog's logic about bones.\n",
 'No warder at the gate \\nCan let the friendly in; \n',
 'Have you practis\xe2\x80\x99d so long to learn to read? \\nHave you felt so proud to get at the meaning of poems?\n',
 'Her glance is calm and commanding - she tosses the slouch of her hat away from her forehead; \\nThe sun falls on her crispy hair  - falls on the black of her polish\xe2\x80\x99d and perfect limbs.\n',
 'This time everyone has the best intentions. \\nThis is the essence of love and failure.\n',
 "Look at the light through the windowpane. \\nThat means it's noon, that means we're inconsolable.\n",
 'I had to make up all the words myself. \\nThe way they taste, the way they sound in the air.\n',
 'In this part of the story I am the one who dies, the only one, and I will die of love because I love you, \\nBecause I love you, Love, in fire and blood. \n',
 'Death arrives among all that sound, like a shoe with no foot in it, like a suit with no man in it, \\nComes and knocks, using a ring with no stone in it, with no finger in it,\n',
 'Death comes and shouts with no mouth, with no tongue, with no throat. \\nNevertheless its steps can be heard and its clothing makes a hushed sound, like a tree.\n',
 'It blows out a mournful sound that swells the sheets, \\nAnd the beds go sailing toward a port where death is waiting, dressed like an admiral.\n',
 'Every tunnel has a light at the end. \\nI will be your lantern to guide the way; cling to me and I will keep you from the darkness.\n',
 'I fly the flight of the fluid and swallowing soul; \\nMy course runs below the soundings of plummets.\n',
 'To make something beautiful should be enough. \\nIt isn\xe2\x80\x99t.\n',
 'A child said, What is the grass? fetching it to me with full hands; \\nHow could I answer the child? I do not know what it is, any more than he.\n',
 'To elaborate is no avail - learn\xe2\x80\x99d and unlearn\xe2\x80\x99d feel that it is so. \\nSure as the most certain sure, plumb in the uprights, well entretied, braced in the beams, \n',
 'If the window is on your right, you are in your own bed. \\nIf the window is over your heart, and it is painted shut, then we are breathing river water.\n',
 'Tell me how all this, and love too, will ruin us. \\nThese, our bodies, possessed by light.\n',
 'Knowing you are faithless keeps me alive and hungry. \\nKnowing you faithful would kill me with joy.\n',
 'For me the man that is proud, and feels how it stings to be slighted; \\nFor me the sweet-heart and the old maid - for me mothers, and the mothers of mothers; \n',
 'Prodigal, you have given me love! Therefore I to you give love! \\nOh unspeakable, passionate love! \n',
 'Have you heard that it was good to gain the day? \\nI also say it is good to fall - battles are lost in the same spirit in which  they are won.\n',
 'We also ascend, dazzling and tremendous as the sun. \\nWe found our own, oh my Soul, in the calm and cool of the daybreak.\n',
 "Tell me how all this, and love too, will ruin us. \\nTell me we'll never get used to it.\n",
 'I know history. \\nThere are many names in history but none of them are ours.\n',
 'There is no way to make this story interesting. \\nA pause, a road, the taste of grave in the mouth.\n',
 "You want a better story. \\nWho wouldn't?\n",
 'You still get to be the hero. \\nWhat more do you want?\n',
 "Do you love yourself? \\nI don't have to answer that.\n",
 "I'm in a helicopter. \\nI have a megaphone and you play along, because you want to die for love, you always have.\n",
 "Thelma\xe2\x80\x99s driving, and Louise's bleeding shotgun into the upholstery. \\nIt's a road movie, a double-feature, two girls striking out across America, While desire, like a monster, crawls up out of the lake with all of us watching.\n",
 'The fear: that nothing survives. \\nThe greater fear: that something does.\n']
    positive_5 = ['The deer imagine they are safe. \\nThe arrows: they have no imagination.\n',
 'If you have children, you will love them more than anything else in the world, more than patriotism, more than democracy. \\nIf your children grow up, and prove traitors to the people, will you be able to demand their deaths, as the Romans did? \n',
 "No ruler in the history of the world has ever been able to afford a war. \\nThey're not affordable things. \n",
 'Pathless the gulf of feeling yawns; no trivial bridge of words, or arch of boldest span, \\nCan leap the moat that girds the sincere man. \n',
 "There's nothing in the world I know \\nThat can escape from love, \n",
 'Implacable is Love \\nFoes may be bought or teased from their hostile intent.\n',
 'The sun is blocked by the sound of our own doubt, \\nWhere is the end of all this?\n',
 'Life is many things. \\nBut you are not alone for I am here.\n',
 'The atmosphere is not a perfume - it has no taste of the distillation - it is odorless; \\nIt is for my mouth forever - I am in love with it.\n',
 'There was never any more inception than there is now, \\nNor any more youth or age than there is now.\n',
 'There will never be any more perfection than there is now, \\nNor any more heaven or hell than there is now.\n',
 'Swiftly arose and spread around me the peace and knowledge that pass all the argument of the earth; \\nAnd that a kelson of the creation is love.\n',
 'Over-hand the hammers swing - over-hand so slow - over-hand so sure: \\nThey do not hasten - each man hits in his place.\n',
 'This is the far-off depth and height reflecting my own face; \\nThis is the thoughtful merge of myself, and the outlet again.\n',
 'It alone is without flaw - it rounds and completes all; \\nThat mystic, baffling wonder I love, alone completes all.\n',
 'One day I tied my hair back with a ribbon and you said that I looked almost like a puritan lady, \\nAnd what I remember best is that the door to your room was the door to mine.',
 'Some of these things are true and some of them lies. \\nBut they are all good stories.\n',
 'And I expect that you know that, and that you think about it in the silence of the night. \\nThere is a pause, while she turns the great pages of her volume of rage, and puts her finger on just the right word.\n',
 'I resist anything better than my own diversity; \\nI breathe the air, but leave plenty after me.\n',
 'You don\xe2\x80\x99t, I say, you don\xe2\x80\x99t owe me squat, let\xe2\x80\x99s just get going, let\xe2\x80\x99s just get gone, but she\xe2\x80\x99s relentless, keeps saying I owe you, says \\nYour shoes are filling with your own damn blood, you must want something, just tell me, and it\xe2\x80\x99s yours. \n',
 'No, I wasn\xe2\x80\x99t meant to love and be loved. \\nIf I\xe2\x80\x99d lived longer, I would have waited longer.\n',
 'O, but with mine, compare thou thine own state, \\nAnd thou shalt find it merits not reproving.\n',
 'No speech, though kind, has it; \\nBut kinder silence doles unto its mates.\n',
 'The smoke of my own breath; \\nEchoes, ripples, buzz\xe2\x80\x99d whispers, love-root, silk-thread, crotch and vine.\n',
 'Backward I see in my own days where I sweated through fog with linguists and contenders; \\nI have no mockings or arguments - I witness and wait.\n',
 'For me lips that have smiled, eyes that have shed tears; \\nFor me children, and the begetters of children.\n',
 'The snow-sleighs, the clinking, shouted jokes, pelts of snowballs; \\nThe hurrahs for popular favorites, the fury of roused mobs.\n',
 'Not one is dissatisfied - not one is demented with the mania of owning things; \\nNot one kneels to another, nor to his kind that lived thousands of years ago.\n',
 'If neither foes nor loving friends can hurt you, \\nIf all men count with you, but none too much...\n',
 'With music strong I come - with my cornets and my drums, \\nI play not marches for accepted victors only - I play great marches for  conquer\xe2\x80\x99d and slain people.\n',
 'She slept the world. \\nSinging god, how was that first sleep so perfect that she had no desire ever to wake?\n',
 'Oh I perceive after all so many uttering tongues! \\nAnd I perceive they do not come from the roofs of mouths for nothing.\n',
 "Tonight you're thinking of cities under crowns of snow and I stare at you like I'm looking through a window, counting birds. \\nYou wanted happiness.\n",
 'I celebrate myself; and what I assume you shall assume; \\nFor every atom belonging to me, as good belongs to you.\n',
 'Stop this day and night with me, and you shall possess the origin of all poems; \\nYou shall possess the good of the earth and sun.\n',
 'I peruse manifold objects, no two alike, and every one good; \\nThe earth good, and the stars good, and their adjuncts all good.\n',
 'Dancing and laughing along the beach came the twenty-ninth bather; \\nThe rest did not see her, but she saw them and loved them.\n',
 'Something I cannot see puts upward libidinous prongs. \\nSeas of bright juice suffuse heaven.\n',
 "And here is the tabernacle reconstructed. \\nHere is the part where everyone was happy all the time and we were all forgiven, even though we didn't deserve it.\n",
 'I try and try. \\nA happy ending?\n']
    libraries = [negative_5, negative_4, negative_3, negative_2, negative_1, zero, positive_1, positive_2, positive_3, positive_4, positive_5]
    if random.random() > 0.7:
        if random.random() >= 0.5:
            mood_meter += 1
        else:
            mood_meter -= 1
    else:
        if TextBlob(text).sentiment.polarity < 0:
            mood_meter -= 1
        elif TextBlob(text).sentiment.polarity > 0:
            mood_meter += 1
        else:
            if neutral_counter < 5:
                neutral_counter += 0
            else:
                if random.random() > 0.5:
                    mood_meter += 1
                else:
                    mood_meter -= 1
    if mood_meter > 5:
        return render_template("transformed_final.html")
    elif mood_meter < -5:
        return render_template("deformed_final.html")
    chosen_library = libraries[mood_meter + 5]
    couplet = random.choice(chosen_library)
    poem = poem + couplet + "\n"
    if mood_meter >= 0:
        return render_template("transformed.html", output=poem.decode('string_escape'))
    elif mood_meter < 0:
        return render_template("deformed.html", output=poem.decode('string_escape'))

if __name__ == '__main__':
    app.debug = True
    app.run()